name: Build, Test, Push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    name: Build, Test, and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Give execute permission to mvnw
        run: chmod +x mvnw  # Give execution permission to mvnw

      - name: Build with Maven
        run: ./mvnw clean package  # Use 'mvnw' for Linux
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}  # Use the environment-provided JAVA_HOME

      - name: Run Tests
        run: ./mvnw test  # Use 'mvnw' for Linux

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run JMeter Tests - APITest.jmx
        run: jmeter -n -t APITest.jmx -l api-test-results.jtl

      - name: Upload API Test Results
        uses: actions/upload-artifact@v2
        with:
          name: api-test-results
          path: api-test-results.jtl

      - name: Run JMeter Tests - View Test Results.jmx
        run: jmeter -n -t 'View Test Results.jmx' -l view-test-results.jtl

      - name: Upload View Test Results
        uses: actions/upload-artifact@v2
        with:
          name: view-test-results
          path: view-test-results.jtl
        

      - name: Build and Push Docker Image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ahmetarslann/messenger-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platform: linux/amd64
          tags: latest

      
