name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ahmetarslann
  DOCKER_HUB_REPOSITORY: messenger-app
  IMAGE_TAG: latest

jobs:
  build_and_push:
    runs-on: windows-latest   # Use Windows runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvnw.cmd package  # Use 'mvnw.cmd' for Windows

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
