name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ahmetarslann
  DOCKER_REPOSITORY: messenger-app
  IMAGE_TAG: latest

jobs:
  build_and_push:
    runs-on: windows-latest   # Use Windows runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: |
          ./mvnw.cmd package  # Use 'mvnw.cmd' for Windows
        env:
          JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt_jdk\11.0.19-7\x64

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
