name: Build and Dockerize

on:
  push:
    branches:
      - master

jobs:
  build-and-dockerize:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and package JAR
      run: cmd /c "mvnw.cmd package -DskipTests"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ahmetarslann/messenger-app:latest

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Push Docker image to Docker Hub
      run: docker push ahmetarslann/messenger-app:latest
