name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest   # Use Linux runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: |
          ./mvnw package  # Use 'mvnw' for Linux
        env:
          JAVA_HOME: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
          
      - name: Build and Push Docker Image to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ahmetarslann/messenger-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platform: linux/amd64
          tags: latest
